title: Alexsandro Silva Alves
email: alexsando.s.alves@gmail.com
description: Tech Lead | Staff Front-End Engineer

baseurl: ""
# url: "https://alexsandro-sa.com.br" # the base hostname & protocol for your site, e.g. http://example.com

# ============================================
# ğŸŒ Language / i18n Settings
# ============================================
# Default language (used when page.lang is not set)
lang: "pt-BR"

# Available languages
languages:
  - code: "pt-BR"
    name: "PortuguÃªs"
    flag: "ğŸ‡§ğŸ‡·"
    default: true
  - code: "en"
    name: "English"
    flag: "ğŸ‡ºğŸ‡¸"
  - code: "es"
    name: "EspaÃ±ol"
    flag: "ğŸ‡ªğŸ‡¸"

# theme: luma-jekyll
remote_theme: AlexsandroSA/luma-jekyll

# Social networks accounts
github_username: AlexsandroSA
twitter_username: alexsandro_sa
codewars_username: AlexsandroSA

# Comments settings
disqus:
  shortname: alexsandrosilvaalves

# Analytics settings
google_analytics: UA-56706328-1

# Build settings
markdown: kramdown
permalink: /:title/

# SEO
logo: /assets/img/brand.png
social:
  name: Alexsandro Silva Alves
  links:
    - https://twitter.com/alexsandro_sa
    - https://www.linkedin.com/in/alexsandrosa
    - https://github.com/AlexsandroSA
author:
  twitter: alexsandro_sa
facebook:
  app_id: 1826465727382348

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Compress: html minify
compress_html:
  clippings: all
  comments: all
  endings: []

future: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
